# Generated by Django 5.0.6 on 2024-08-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0003_sodaorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SodaOrder',
            new_name='Soda_Order',
        ),
    ]
