# Generated by Django 5.0.6 on 2024-08-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0006_alcohol_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreakfastOrder',
            new_name='Breakfast_Order',
        ),
        migrations.RenameModel(
            old_name='LunchOrder',
            new_name='Lunch_Order',
        ),
        migrations.RenameModel(
            old_name='SupperOrder',
            new_name='Supper_Order',
        ),
    ]
