# Generated by Django 5.0.6 on 2024-08-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0007_rename_breakfastorder_breakfast_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supper_Order',
            new_name='Food_Order',
        ),
        migrations.DeleteModel(
            name='Breakfast_Order',
        ),
        migrations.DeleteModel(
            name='Lunch_Order',
        ),
    ]
