# Generated by Django 5.1.1 on 2024-09-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0008_rename_supper_order_food_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item_type', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('table_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item_type', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('table_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item_type', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('table_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Food_Order',
        ),
    ]
