# Generated by Django 5.1.1 on 2024-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0009_breakfast_lunch_supper_delete_food_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfast',
            old_name='food_item_type',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='food_item_type',
            new_name='food_type',
        ),
        migrations.RemoveField(
            model_name='supper',
            name='food_item_type',
        ),
        migrations.AddField(
            model_name='supper',
            name='food_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
