# Generated by Django 5.1.1 on 2024-09-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0011_soda_water_rename_alcohol_order_energydrink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfast',
            old_name='food_type',
            new_name='food_item',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='food_type',
            new_name='food_item',
        ),
        migrations.RenameField(
            model_name='supper',
            old_name='food_type',
            new_name='food_item',
        ),
    ]
