# Generated by Django 5.1.1 on 2024-09-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0014_breakfast_created_at_energydrink_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('supper', 'Supper')], max_length=10)),
                ('food_type', models.CharField(max_length=255)),
                ('number_of_people', models.PositiveIntegerField()),
                ('table_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Breakfast',
        ),
        migrations.DeleteModel(
            name='Energydrink',
        ),
        migrations.DeleteModel(
            name='Juices',
        ),
        migrations.DeleteModel(
            name='Lunch',
        ),
        migrations.DeleteModel(
            name='Soda',
        ),
        migrations.DeleteModel(
            name='Supper',
        ),
        migrations.DeleteModel(
            name='Water',
        ),
    ]
