# Generated by Django 5.1.1 on 2024-09-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0016_breakfast_energydrink_juices_lunch_soda_supper_water_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfast',
            old_name='food_item',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='breakfast',
            old_name='created_at',
            new_name='timestamps',
        ),
        migrations.RenameField(
            model_name='energydrink',
            old_name='food_item',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='juices',
            old_name='food_item',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='food_item',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='created_at',
            new_name='timestamps',
        ),
        migrations.RenameField(
            model_name='soda',
            old_name='food_item',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='soda',
            old_name='created_at',
            new_name='timestamps',
        ),
        migrations.RenameField(
            model_name='supper',
            old_name='food_item',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='supper',
            old_name='created_at',
            new_name='timestamps',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='food_item',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='created_at',
            new_name='timestamps',
        ),
    ]
