# Generated by Django 5.1.2 on 2024-10-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0024_alter_drinksitem_category_alter_fooditem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Josh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('pass1', models.CharField(max_length=50)),
                ('pass2', models.CharField(max_length=50)),
            ],
        ),
    ]
