# Generated by Django 5.1.2 on 2024-11-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0027_alcoholicdrinksitem_beers_whiskeys_wines_delete_josh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholicdrinksitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
