# Generated by Django 5.1.2 on 2024-11-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0028_alter_alcoholicdrinksitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
