# Generated by Django 5.1.2 on 2024-11-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
