# Generated by Django 5.1.2 on 2024-12-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0032_chips_masala_plain_chips'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Plain Chips', 'Plain Chips'), ('Chips Masala', 'Chips Masala')], default='Choose Category', max_length=50)),
            ],
        ),
    ]
