# Generated by Django 5.1.2 on 2025-01-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0035_burgers_edit_fast_foodsitem_pizza_sand_wich_taccos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beers',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='burgers',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chips_masala',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='energydrink',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='juices',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plain_chips',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sand_wich',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='soda',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supper',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taccos',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='water',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='whiskeys',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wines',
            name='table_number',
            field=models.IntegerField(),
        ),
    ]
