# Generated by Django 5.0.6 on 2024-08-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0004_rename_sodaorder_soda_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Soda_Order',
            new_name='SoftDrink_Order',
        ),
    ]
