# Generated by Django 5.1.1 on 2024-09-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0012_rename_food_type_breakfast_food_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='energydrink',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='juices',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='soda',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='supper',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='water',
            name='timestamp',
        ),
    ]
