# Generated by Django 5.1.2 on 2024-10-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0017_rename_food_item_breakfast_food_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supper',
            old_name='timestamps',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supper',
            name='table_number',
            field=models.IntegerField(),
        ),
    ]
