# Generated by Django 5.1.2 on 2024-10-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0021_alter_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Water', 'Water'), ('Soda', 'Soda'), ('Juices', 'Juices'), ('Energy Drinks', 'Energy Drinks')], default='Choose Category', max_length=50),
        ),
    ]
