# Generated by Django 5.1.2 on 2024-10-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0023_drinksitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinksitem',
            name='category',
            field=models.CharField(choices=[('Water', 'Water'), ('Soda', 'Soda'), ('Juices', 'Juices'), ('Energy Drinks', 'Energy Drinks')], default='Choose Category', max_length=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper')], default='Choose Category', max_length=50),
        ),
    ]
