# Generated by Django 5.1.2 on 2024-11-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0026_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='alcoholicDrinksItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Beers', 'Beers'), ('Wines', 'Wines'), ('Whiskeys', 'Whiskeys')], default='Choose Category', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Beers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('food_type', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whiskeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('food_type', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('food_type', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Josh',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
