# Generated by Django 5.1.2 on 2024-12-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0031_rename_created_at_energydrink_timestamps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chips_Masala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('food_type', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plain_Chips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('food_type', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
