# Generated by Django 5.1.2 on 2024-12-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0033_chipsitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChipsItem',
            new_name='edit_chipsItem',
        ),
    ]
