# Generated by Django 5.1.2 on 2025-01-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0036_alter_beers_table_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plain_Chips',
            new_name='Chips',
        ),
        migrations.DeleteModel(
            name='Chips_Masala',
        ),
        migrations.DeleteModel(
            name='edit_chipsItem',
        ),
        migrations.AlterField(
            model_name='edit_fast_foodsitem',
            name='category',
            field=models.CharField(choices=[('Burgers', 'Burgers'), ('Taccos', 'Taccos'), ('Pizza', 'Pizza'), ('Sand Wiches', 'Sand Wiches'), ('Chips', 'Chips')], default='Choose Category', max_length=50),
        ),
    ]
