# Generated by Django 5.1.3 on 2025-02-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0037_rename_plain_chips_chips_delete_chips_masala_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('pass1', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('pass1', models.CharField(max_length=255)),
                ('pass2', models.CharField(max_length=255)),
            ],
        ),
    ]
