# Generated by Django 5.1.3 on 2025-03-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0040_alter_notification_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energydrink',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juices',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soda',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='water',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
